services:
  server:
    hostname: "${SERVICE_HOSTNAME}"
    container_name: plex-api-dev
    command: npm run dev
    environment:
      NODE_ENV: "${NODE_ENV}"
      PLEX_SERVER_PROTOCOL: "${PLEX_SERVER_PROTOCOL}"
      PLEX_SERVER_IP: "${PLEX_SERVER_IP}"
      PLEX_SERVER_PORT: "${PLEX_SERVER_PORT}"
      PLEX_SERVER_TOKEN: "${PLEX_SERVER_TOKEN}"
      PLEX_CLIENT_IDENTIFIER: "${PLEX_CLIENT_IDENTIFIER}"
      PLEX_SERVER_URL: "${PLEX_SERVER_URL}"
